### ISSUE TITLE
Chrome Rendering Bug

### ISSUE THREAD

**Issue by alanhdu** [alanhdu/hunt#37]
It seems that Chrome no longer renders our square font correctly:

![screenshot from 2015-02-25 11 01 01](https://cloud.githubusercontent.com/assets/1914111/6374286/ee689222-bcdd-11e4-82a0-50a3f77893ee.png)

As opposed to Firefox:
![screenshot from 2015-02-25 11 01 52](https://cloud.githubusercontent.com/assets/1914111/6374291/f65023e2-bcdd-11e4-974a-a6f345c7fef6.png)

**Comment by alanhdu** [comment]
Disabling square font for now, until I find a fix.

**Comment by samm81** [comment]
woah
how'd you bring it back online?
the last couple of times I tried to access it it was down

**Comment by alanhdu** [comment]
Turns out in chrome, `&nbsp;` has a different width than ` `. Using a `<pre>` tag with spaces solves the problem.

**Comment by alanhdu** [comment]
A couple of things went wrong:
* A stupid tuple unpacking error. Don't know why I didn't catch this before
* Gunicorn update problem. Latest version didn't work, had to downgrade.

**Comment by samm81** [comment]
How do I get in contact with you
You don't check your chat

**Comment by alanhdu** [comment]
Ah...sorry about that. Just send me email sometime. I should get a notification on my phone when that hapens.
