### ISSUE TITLE
People joining don't necessarily go to the same game

### ISSUE THREAD

**Issue by samm81** [alanhdu/hunt#40]
I'm not really sure what's happening here. I don't know if the server gives up on one of them, or generates a separate world, or something.

**Comment by alanhdu** [comment]
Hm...that's very weird. The requisite log-in code is https://github.com/alanhdu/hunt/blob/master/server.py#L53:

```Python
 53 @socketio.on("begin")
 54 def begin(msg):
 55     if "username" in session:
 56         raise excpt.AlreadyLoggedIn()
 57     elif msg["username"] in game.players:
 58         raise excpt.UsernameTaken(msg["username"])
 59     else:
 60         game.addPlayer(msg["username"])
 61         session["username"] = msg["username"]
 62         join_room(msg["username"])
 63 
 64         socketio.emit("acknowledged", {}, room=msg["username"])
 65 
 66     global running
 67     if running is None:
 68         running = gevent.spawn(run)
```

`game` is a global variable that is only initialized once, so everybody should go to the same game. So I have two possible explanations:
* Something's up with `running`. Running was a little hack to make sure we didn't waste cycles updating the game when there were no players. I'll kill this with something a little cleaner.
* Maybe it's a heroku thing? If this is the case, I'm not sure what to do.

**Comment by alanhdu** [comment]
Let's see if cd3cf6b9261bd266d7f4e9d6dc469c3460a83c97 fixes things.

**Comment by samm81** [comment]
Seems to!
